DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS quotes;
DROP TABLE IF EXISTS todos;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS products;
